### ISSUE TITLE
Expected behaviour?

### ISSUE THREAD

**Issue by janegilring** [kmhuglen/ardoq#1]
I' m testing the module against a test-org/test-workspace, and get a single long string (3,3 million characters) instead of objects as I was expecting:

PS C:\> $test = Get-ArdoqComponent -WorkspaceID $WorkspaceID

PS C:\> $test.Count
1

PS C:\> $test.Length
3336629

I then tried to pipe the string to ConvertFrom-Json:
PS C:\> $test | ConvertFrom-Json
ConvertFrom-Json : Cannot convert the JSON string because a dictionary that was converted from the string contains the duplicated 
keys 'jirabacklogCount' and 'jiraBacklogCount'.

Is this expected behavior, or could there have been any API changes since the module was created causing this?

**Comment by kmhuglen** [comment]
This is one of my first PowerShell modules, and it was never used in production. It has not been tested since I published it on GitHub, so there is probably an error in the module. :-)

**Comment by janegilring** [comment]
I see, I`ll dig into the underlying Invoke-RestMethod calls and see if I can figure out what's going on.
If I find any bugs I'll create a pull request :-)
